# Generated by Django 4.2.3 on 2023-07-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0002_alter_order_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
