# Generated by Django 4.2.3 on 2023-07-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklad', '0003_alter_staff_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condractor_on_stock',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='condractor_on_stock',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
